[project]
name = "ki-test"
version = "0.1.0"
description = "own implementation of a DNA-like algorithm for atari's space-invaders"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ale-py>=0.11.2",
    "gymnasium>=1.2.0",
    "torch>=2.8.0",
]
